### ISSUE TITLE
Elenco comuni per province con spazi ritornano un array vuoto

### ISSUE THREAD

**Issue by mattiamusazzi** [Samurai016/comuni-ita#2]
Salve,
abbiamo riscontrato un problema con l'ottenimento dei comuni per le province che contengono spazi.
Ad esempio:
https://axqvoqvbfjpaamphztgd.functions.supabase.co/comuni/provincia/Pesaro%20e%20Urbino
Torna un array vuoto.
Mentre
https://axqvoqvbfjpaamphztgd.functions.supabase.co/comuni/provincia/Milano
funziona.
Ci può supportare gentilmente?
Grazie!

**Comment by Samurai016** [comment]
Fixato, era un problema legato alla decodifica del parametro.
