### ISSUE TITLE
Comuni Duplicati

### ISSUE THREAD

**Issue by IlChitarrista** [Samurai016/comuni-ita#4]
Alcuni comuni sono duplicati, questo crea problemi in fase di filtering, a breve compilerò una lista dei duplicati.

**Comment by IlChitarrista** [comment]
Ci sono alcuni comuni che sono duplicati con una minima variazione di dati, suppongo che questo sia inteso, errore mio.

**Comment by Samurai016** [comment]
Ciao @IlChitarrista , ho visto, ci sono 10 comuni diversi tra loro ma omonimi, in regioni/province diverse, è una curiosità del nostro Paese.
I comuni omonimi, per informazione, sono:
| Nome | Provincia |
| -- | -- |
| [Peglio](https://it.wikipedia.org/wiki/Peglio_(Lombardia)) | Como |
| [Peglio](https://it.wikipedia.org/wiki/Peglio_(Marche)) | Pesaro e Urbino |
| [Livo](https://it.wikipedia.org/wiki/Livo_(Lombardia)) | Como |
| [Livo](https://it.wikipedia.org/wiki/Livo_(Trentino-Alto_Adige)) | Trento |
| [San Teodoro](https://it.wikipedia.org/wiki/San_Teodoro_(Sicilia)) | Messina |
| [San Teodoro](https://it.wikipedia.org/wiki/San_Teodoro_(Sardegna)) | Sassari |
| [Samone](https://it.wikipedia.org/wiki/Samone_(Piemonte)) | Torino |
| [Samone](https://it.wikipedia.org/wiki/Samone_(Trentino-Alto_Adige)) | Trento |
| [Castro](https://it.wikipedia.org/wiki/Castro_(Lombardia)) | Bergamo |
| [Castro](https://it.wikipedia.org/wiki/Castro_(Puglia)) | Lecce |
