### ISSUE TITLE
Comuni mancanti

### ISSUE THREAD

**Issue by sfabruz** [Samurai016/comuni-ita#5]
Ciao!
Complimenti per il progetto e grazie per l'API!
Vorrei sapere ogni quanto vengono aggiornati i dati di comuni/province perché vedo che ne mancano diversi.
Ad esempio sulla sardegna, all'endpoint
```
https://axqvoqvbfjpaamphztgd.functions.supabase.co/province/sardegna
```
mi vengono restituite 5 province mentre su questo sito http://www.comuni-italiani.it/20/ ne vengono restituite 8.
Questo sito è solo un esempio, ho visto la stessa cosa anche su altri.

Di nuovo grazie mille

**Comment by Samurai016** [comment]
Ciao @sfabruz 
I dati vengono aggiornati ogni 6 mesi (febbraio/agosto) sulla base del file excel pubblicato e aggiornato dall'ISTAT (I dati poi vengono incrociati con altri dati provenienti dal Ministero dell'interno (email, PEC, telefono) e da Wikidata (cap, prefisso telefonico e coordinate).

Per quanto riguarda le province sarde, la Sardegna è dal 2021 in uno stato in cui stanno cambiando le province, una serie di leggi regionali hanno istituito nuove province e soppresse altre.
Ad oggi però sono ancora in fase di attivazione e infatti anche Wikipedia riporta la suddivisione in 5 province e i comuni vengono ancora segnalati come appartenenti alle 5 province.
Io per consistenza dei dati e di fonti ho preferito utilizzare i dati ISTAT (in cui risultano ancora le sole 5 province).
Quando l'ISTAT aggiorneranno i dati (presumibilmente nel momento in cui le nuove province diventeranno attive) anche l'API si aggiornerà.
Nel peggiore dei casi (aggiornamento dei dati ISTAT il giorno dopo che l'API si aggiorna), l'API risulterà sfasata per 6 mesi, a meno che io o qualcuno si accorga del problema e segnalandolo io posso avviare manualmente la procedura di aggiornamento.

Spero di esserti stato di aiuto!
Nel caso sono a disposizione per chiarimenti.

**Comment by sfabruz** [comment]
Chiarissimo, grazie mille
